---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-jamf-prod
spec:
  destination:
    namespace: go-jamf-prod
    name: production
  project: default
  source:
    path: apps/go-jamf
    repoURL: https://github.com/mimotej/jamf-manifests.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      allowEmpty: true
