---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-jamf.name" . }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Values.env.instance }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
