---
replicaCount: 1
image:
  repository: mimotej/go-jamf
  tag: "pr-2-6f56f6dbc9faa8549c404c4a4a8ed2e527038f60"
namespace: go-jamf-dev
nameOverride: ""

service:
  name: http
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  pathType: Prefix
  hosts:
    - host: go-jamf-dev.internal
      paths:
        - path: /
  #tls:
  #  - secretName: go-jamf-tls
  #    hosts:
  #      - go-jamf-dev.internal
env:
  name: dev
