---
replicaCount: 1
image:
  repository: mimotej/go-jamf
  tag: "1.1.0"
namespace: go-jamf-prod
nameOverride: ""
service:
  name: http
  type: ClusterIP
  port: 80
  targetPort: 8080
ingress:
  enabled: true
  className: nginx
  pathType: Prefix
  hosts:
  host: go-jamf.internal
  path: /
  #tls:
  #  - secretName: go-jamf-tls
  #    hosts:
  #      - go-jamf.internal
env:
  name: prod
  instance: go-jamf-prod
