---
replicaCount: 1
image:
  repository: mimotej/go-jamf
  tag: "pr--21cecd91a8b51712d06be725f732a12906f7b003"
namespace: go-jamf-dev
nameOverride: ""
service:
  name: http
  type: ClusterIP
  port: 80
  targetPort: 8080
ingress:
  enabled: true
  className: nginx
  pathType: Prefix
  host: go-jamf-dev.internal
  path: /
  #tls:
  #  - secretName: go-jamf-tls
  #    hosts:
  #      - go-jamf-dev.internal
env:
  name: dev
  instance: go-jamf-dev
