---
name: Lint YAML files
runs:
  using: 'composite'
  steps:
    - name: 'Yamllint'
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_strict: false
        yamllint_comment: false
    - name: Lint Helm charts
      uses: helm/chart-testing-action@v2.6.1
      with:
        command: lint
        config: ct.yaml
